-- Phase 4: AI Analysis - News and Sentiment Tables
-- Migration 004: News storage and AI analysis cache

-- Stock news table
CREATE TABLE IF NOT EXISTS stock_news (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    symbol VARCHAR(10) NOT NULL,
    title TEXT NOT NULL,
    summary TEXT,
    content TEXT,
    source VARCHAR(50) NOT NULL DEFAULT 'cnyes', -- cnyes = 鉅亨網
    source_url TEXT,
    published_at TIMESTAMP WITH TIME ZONE NOT NULL,
    fetched_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    
    -- Sentiment analysis results
    sentiment VARCHAR(20), -- positive, negative, neutral
    sentiment_score DECIMAL(5,4), -- -1.0 to 1.0
    sentiment_analyzed_at TIMESTAMP WITH TIME ZONE,
    
    -- Metadata
    category VARCHAR(50), -- 個股, 產業, 總經, etc.
    tags TEXT[], -- Array of tags
    
    UNIQUE(source, source_url)
);

-- Index for fast lookups
CREATE INDEX IF NOT EXISTS idx_stock_news_symbol ON stock_news(symbol);
CREATE INDEX IF NOT EXISTS idx_stock_news_published_at ON stock_news(published_at DESC);
CREATE INDEX IF NOT EXISTS idx_stock_news_symbol_date ON stock_news(symbol, published_at DESC);
CREATE INDEX IF NOT EXISTS idx_stock_news_sentiment ON stock_news(sentiment) WHERE sentiment IS NOT NULL;

-- AI analysis cache table
CREATE TABLE IF NOT EXISTS ai_analysis_cache (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    symbol VARCHAR(10) NOT NULL,
    analysis_type VARCHAR(50) NOT NULL, -- daily_summary, investment_advice, risk_assessment
    analysis_date DATE NOT NULL,
    
    -- Analysis content
    content TEXT NOT NULL,
    model VARCHAR(50) NOT NULL, -- gpt-4o-mini, gpt-4o, etc.
    
    -- Metadata
    input_tokens INTEGER,
    output_tokens INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP WITH TIME ZONE,
    
    UNIQUE(symbol, analysis_type, analysis_date)
);

CREATE INDEX IF NOT EXISTS idx_ai_analysis_symbol ON ai_analysis_cache(symbol);
CREATE INDEX IF NOT EXISTS idx_ai_analysis_date ON ai_analysis_cache(analysis_date DESC);
CREATE INDEX IF NOT EXISTS idx_ai_analysis_expires ON ai_analysis_cache(expires_at) WHERE expires_at IS NOT NULL;

-- Stock alerts table (for anomaly detection)
CREATE TABLE IF NOT EXISTS stock_alerts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    symbol VARCHAR(10) NOT NULL,
    alert_type VARCHAR(50) NOT NULL, -- volume_spike, price_breakout, sentiment_shift, etc.
    severity VARCHAR(20) NOT NULL, -- info, warning, critical
    
    -- Alert details
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    data JSONB, -- Additional structured data
    
    -- Timestamps
    triggered_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    acknowledged_at TIMESTAMP WITH TIME ZONE,
    acknowledged_by UUID,
    
    -- Reference data
    reference_price DECIMAL(10,2),
    reference_volume BIGINT,
    threshold_value DECIMAL(10,4)
);

CREATE INDEX IF NOT EXISTS idx_stock_alerts_symbol ON stock_alerts(symbol);
CREATE INDEX IF NOT EXISTS idx_stock_alerts_type ON stock_alerts(alert_type);
CREATE INDEX IF NOT EXISTS idx_stock_alerts_triggered ON stock_alerts(triggered_at DESC);
CREATE INDEX IF NOT EXISTS idx_stock_alerts_unack ON stock_alerts(symbol, triggered_at DESC) WHERE acknowledged_at IS NULL;

-- News fetch log (to track crawling progress)
CREATE TABLE IF NOT EXISTS news_fetch_log (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    source VARCHAR(50) NOT NULL,
    symbol VARCHAR(10),
    fetched_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    articles_found INTEGER DEFAULT 0,
    articles_new INTEGER DEFAULT 0,
    status VARCHAR(20) NOT NULL, -- success, failed, partial
    error_message TEXT,
    duration_ms INTEGER
);

CREATE INDEX IF NOT EXISTS idx_news_fetch_log_source ON news_fetch_log(source, fetched_at DESC);
CREATE INDEX IF NOT EXISTS idx_news_fetch_log_symbol ON news_fetch_log(symbol, fetched_at DESC) WHERE symbol IS NOT NULL;

-- Comments
COMMENT ON TABLE stock_news IS 'Stores news articles related to stocks for sentiment analysis';
COMMENT ON TABLE ai_analysis_cache IS 'Caches AI-generated analysis to reduce API costs';
COMMENT ON TABLE stock_alerts IS 'Stores alerts generated by anomaly detection';
COMMENT ON TABLE news_fetch_log IS 'Tracks news crawling history for debugging and rate limiting';
